"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var User_1 = require("../User/User");
var Shop_1 = require("../Shop/Shop");
var CashRegister_1 = require("../CashRegister/CashRegister");
var Product_1 = require("../Products/Product");
var DecountCards_1 = require("../Loyalty/DecountCards");
var Descount_1 = require("../Loyalty/Descount");
var shop = new Shop_1.Shop("Лента", new Descount_1.Descount("Карты посетителей", new DecountCards_1.DescountCards(10, 15, 20)));
var user = new User_1.User("Oleg");
var pr1 = new Product_1.Product("Хлеб", 100);
var pr2 = new Product_1.Product("Вода", 60);
var pr3 = new Product_1.Product("Черная икра", 5300);
shop.getShopSystem().pushProductsInAssortiment(pr1);
shop.getShopSystem().pushProductsInAssortiment(pr2);
shop.getShopSystem().pushProductsInAssortiment(pr3);
shop.getShopSystem().pushNewUserInShopSystem(user);
shop.getShopSystem().pushProductInUserBasket(user, 0);
shop.getShopSystem().pushProductInUserBasket(user, 1);
var userInd = shop.getIndexUserInShop(user);
var desc = shop.getDescount().getCards().getBronzeCard();
shop.getShopSystem().getUserLoyaltyInShop()[userInd].setDescount(desc);
CashRegister_1.CashRegister.buy(user, shop);
shop.getShopSystem().pushProductInUserBasket(user, 2);
CashRegister_1.CashRegister.buy(user, shop);
